CREATE PROCEDURE [dbo].[spClearDB]
AS
 BEGIN
	TRUNCATE TABLE Orders

	ALTER TABLE Orders DROP CONSTRAINT FK_Orders_Products

	TRUNCATE TABLE Products

	ALTER TABLE Orders
	ADD CONSTRAINT FK_Orders_Products
	FOREIGN KEY (product_id) REFERENCES Products(Id);
 END
GO
